### ISSUE TITLE
Dont have a AutotaskObjectsZoneInfo.php

### ISSUE THREAD

**Issue by Rikgeffen** [opendns/autotask-php#71]
I am missing the following file:
```

Warning: require_once(C:\xampp\htdocs\CM\AT\autotask-php-0.1.10\src\AutotaskObjectsZoneInfo.php): failed to open stream: No such file or directory in C:\xampp\htdocs\CM\AT\autotask-php-0.1.10\src\autoload.php on line 9

Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\CM\AT\autotask-php-0.1.10\src\AutotaskObjectsZoneInfo.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\CM\AT\autotask-php-0.1.10\src\autoload.php on line 9
```

i dont have this file and its not in the download folder?

**Comment by Rikgeffen** [comment]
I see i need to look first. But now if i try this code:

```
require_once __DIR__ . '/src/client.php';
$username = '***********';
$password = '*****';
$authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';
$opts = array('trace' => 1);
$client = new ATWS\Client($authWsdl, $opts);
$zoneInfo = $client->getZoneInfo($username);

print_r($zoneInfo);
```
**Fatal error: Class 'ATWS\AutotaskObjects\ZoneInfo' not found in C:\xampp\htdocs\CM\AT\autotask-php-0.1.10\src\Client.php on line 136**

But how is this posible its the good path and it see the path in the eclipse to.

**Comment by Rikgeffen** [comment]
**I search for the problem and the say its the : <? instead of <?php.
And now i get all of this as output.**

`'ATWS\AutotaskObjects\Account', 'AccountLocation' => 'ATWS\AutotaskObjects\AccountLocation', 'AccountNote' => 'ATWS\AutotaskObjects\AccountNote', 'AccountTeam' => 'ATWS\AutotaskObjects\AccountTeam', 'AccountToDo' => 'ATWS\AutotaskObjects\AccountToDo', 'ActionType' => 'ATWS\AutotaskObjects\ActionType', 'AdditionalInvoiceFieldValue' => 'ATWS\AutotaskObjects\AdditionalInvoiceFieldValue', 'AllocationCode' => 'ATWS\AutotaskObjects\AllocationCode', 'Appointment' => 'ATWS\AutotaskObjects\Appointment', 'ArrayOfATWSError' => 'ATWS\AutotaskObjects\ArrayOfATWSError', 'ArrayOfEntity' => 'ATWS\AutotaskObjects\ArrayOfEntity', 'ArrayOfEntityInfo' => 'ATWS\AutotaskObjects\ArrayOfEntityInfo', 'ArrayOfEntityReturnInfo' => 'ATWS\AutotaskObjects\ArrayOfEntityReturnInfo', 'ArrayOfField' => 'ATWS\AutotaskObjects\ArrayOfField', 'ArrayOfPickListValue' => 'ATWS\AutotaskObjects\ArrayOfPickListValue', 'ArrayOfUserDefinedField' => 'ATWS\AutotaskObjects\ArrayOfUserDefinedField', 'Attachment' => 'ATWS\AutotaskObjects\Attachment', 'AttachmentInfo' => 'ATWS\AutotaskObjects\AttachmentInfo', 'ATWSError' => 'ATWS\AutotaskObjects\ATWSError', 'ATWSResponse' => 'ATWS\AutotaskObjects\ATWSResponse', 'ATWSZoneInfo' => 'ATWS\AutotaskObjects\ATWSZoneInfo', 'AutotaskIntegrations' => 'ATWS\AutotaskObjects\AutotaskIntegrations', 'BillingItem' => 'ATWS\AutotaskObjects\BillingItem', 'BillingItemApprovalLevel' => 'ATWS\AutotaskObjects\BillingItemApprovalLevel', 'ChangeRequestLink' => 'ATWS\AutotaskObjects\ChangeRequestLink', 'ClientPortalUser' => 'ATWS\AutotaskObjects\ClientPortalUser', 'Contact' => 'ATWS\AutotaskObjects\Contact', 'Contract' => 'ATWS\AutotaskObjects\Contract', 'ContractBlock' => 'ATWS\AutotaskObjects\ContractBlock', 'ContractCost' => 'ATWS\AutotaskObjects\ContractCost', 'ContractFactor' => 'ATWS\AutotaskObjects\ContractFactor', 'ContractMilestone' => 'ATWS\AutotaskObjects\ContractMilestone', 'ContractNote' => 'ATWS\AutotaskObjects\ContractNote', 'ContractRate' => 'ATWS\AutotaskObjects\ContractRate', 'ContractRetainer' => 'ATWS\AutotaskObjects\ContractRetainer', 'ContractService' => 'ATWS\AutotaskObjects\ContractService', 'ContractServiceAdjustment' => 'ATWS\AutotaskObjects\ContractServiceAdjustment', 'ContractServiceBundle' => 'ATWS\AutotaskObjects\ContractServiceBundle', 'ContractServiceBundleAdjustment' => 'ATWS\AutotaskObjects\ContractServiceBundleAdjustment', 'ContractServiceBundleUnit' => 'ATWS\AutotaskObjects\ContractServiceBundleUnit', 'ContractServiceUnit' => 'ATWS\AutotaskObjects\ContractServiceUnit', 'ContractTicketPurchase' => 'ATWS\AutotaskObjects\ContractTicketPurchase', 'Country' => 'ATWS\AutotaskObjects\Country', 'CreateAttachment' => 'ATWS\AutotaskObjects\CreateAttachment', 'CreateAttachmentResponse' => 'ATWS\AutotaskObjects\CreateAttachmentResponse', 'createResponse' => 'ATWS\AutotaskObjects\CreateResponse', 'deleteResponse' => 'ATWS\AutotaskObjects\DeleteResponse', 'Department' => 'ATWS\AutotaskObjects\Department', 'Entity' => 'ATWS\AutotaskObjects\Entity', 'EntityDuplicateStatus' => 'ATWS\AutotaskObjects\EntityDuplicateStatus', 'EntityInfo' => 'ATWS\AutotaskObjects\EntityInfo', 'EntityReturnInfo' => 'ATWS\AutotaskObjects\EntityReturnInfo', 'EntityReturnInfoDatabaseAction' => 'ATWS\AutotaskObjects\EntityReturnInfoDatabaseAction', 'ExpenseItem' => 'ATWS\AutotaskObjects\ExpenseItem', 'ExpenseReport' => 'ATWS\AutotaskObjects\ExpenseReport', 'Field' => 'ATWS\AutotaskObjects\Field', 'getUDFInfo' => 'ATWS\AutotaskObjects\UDFParam', 'getUDFInfoResponse' => 'ATWS\AutotaskObjects\UDFInfoResponse', 'InstalledProduct' => 'ATWS\AutotaskObjects\InstalledProduct', 'InternalLocation' => 'ATWS\AutotaskObjects\InternalLocation', 'InventoryItem' => 'ATWS\AutotaskObjects\InventoryItem', 'InventoryItemSerialNumber' => 'ATWS\AutotaskObjects\InventoryItemSerialNumber', 'InventoryLocation' => 'ATWS\AutotaskObjects\InventoryLocation', 'InventoryTransfer' => 'ATWS\AutotaskObjects\InventoryTransfer', 'Invoice' => 'ATWS\AutotaskObjects\Invoice', 'InvoiceMarkup' => 'ATWS\AutotaskObjects\InvoiceMarkup', 'InvoiceTemplate' => 'ATWS\AutotaskObjects\InvoiceTemplate', 'Opportunity' => 'ATWS\AutotaskObjects\Opportunity', 'PaymentTerm' => 'ATWS\AutotaskObjects\PaymentTerm', 'Phase' => 'ATWS\AutotaskObjects\Phase', 'PickListValue' => 'ATWS\AutotaskObjects\PickListValue', 'Product' => 'ATWS\AutotaskObjects\Product', 'ProductVendor' => 'ATWS\AutotaskObjects\ProductVendor', 'Project' => 'ATWS\AutotaskObjects\Project', 'ProjectCost' => 'ATWS\AutotaskObjects\ProjectCost', 'ProjectNote' => 'ATWS\AutotaskObjects\ProjectNote', 'PurchaseOrder' => 'ATWS\AutotaskObjects\PurchaseOrder', 'PurchaseOrderItem' => 'ATWS\AutotaskObjects\PurchaseOrderItem', 'PurchaseOrderReceive' => 'ATWS\AutotaskObjects\PurchaseOrderReceive', 'queryResponse' => 'ATWS\AutotaskObjects\QueryResponse', 'Quote' => 'ATWS\AutotaskObjects\Quote', 'QuoteItem' => 'ATWS\AutotaskObjects\QuoteItem', 'QuoteLocation' => 'ATWS\AutotaskObjects\QuoteLocation', 'Resource' => 'ATWS\AutotaskObjects\Resource', 'ResourceRole' => 'ATWS\AutotaskObjects\ResourceRole', 'Role' => 'ATWS\AutotaskObjects\Role', 'SalesOrder' => 'ATWS\AutotaskObjects\SalesOrder', 'Service' => 'ATWS\AutotaskObjects\Service', 'ServiceBundle' => 'ATWS\AutotaskObjects\ServiceBundle', 'ServiceBundleService' => 'ATWS\AutotaskObjects\ServiceBundleService', 'ServiceCall' => 'ATWS\AutotaskObjects\ServiceCall', 'ServiceCallTask' => 'ATWS\AutotaskObjects\ServiceCallTask', 'ServiceCallTaskResource' => 'ATWS\AutotaskObjects\ServiceCallTaskResource', 'ServiceCallTicket' => 'ATWS\AutotaskObjects\ServiceCallTicket', 'ServiceCallTicketResource' => 'ATWS\AutotaskObjects\ServiceCallTicketResource', 'ShippingType' => 'ATWS\AutotaskObjects\ShippingType', 'Task' => 'ATWS\AutotaskObjects\Task', 'TaskNote' => 'ATWS\AutotaskObjects\TaskNote', 'TaskPredecessor' => 'ATWS\AutotaskObjects\TaskPredecessor', 'TaskSecondaryResource' => 'ATWS\AutotaskObjects\TaskSecondaryResource', 'Tax' => 'ATWS\AutotaskObjects\Tax', 'TaxCategory' => 'ATWS\AutotaskObjects\TaxCategory', 'TaxRegion' => 'ATWS\AutotaskObjects\TaxRegion', 'Ticket' => 'ATWS\AutotaskObjects\Ticket', 'TicketChangeRequestApproval' => 'ATWS\AutotaskObjects\TicketChangeRequestApproval', 'TicketCost' => 'ATWS\AutotaskObjects\TicketCost', 'TicketNote' => 'ATWS\AutotaskObjects\TicketNote', 'TicketSecondaryResource' => 'ATWS\AutotaskObjects\TicketSecondaryResource', 'TimeEntry' => 'ATWS\AutotaskObjects\TimeEntry', 'UserDefinedField' => 'ATWS\AutotaskObjects\UserDefinedField', 'UserDefinedFieldDefinition' => 'ATWS\AutotaskObjects\UserDefinedFieldDefinition', 'UserDefinedFieldListItem' => 'ATWS\AutotaskObjects\UserDefinedFieldListItem', ); // @codeCoverageIgnoreStart public function __construct($wsdl, $soapOpts = array()) { foreach (static::$classMap as $external => $internal) { if (!isset($soapOpts['classmap'][$external])) { $soapOpts['classmap'][$external] = $internal; } } parent::__construct($wsdl, $soapOpts); } public function getZoneInfo($username) { $zoneInfoObject = new \AutotaskObjects\ZoneInfo.php($username); return $this->_call('getZoneInfo', array($zoneInfoObject)); } public function create(AutotaskObjects\Entity $obj) { $params = new AutotaskObjects\CreateParam($obj); return $this->_call('create', array($params)); } public function bulkCreate(array $objs) { if (count($objs) > 200) { throw new \Exception('You can only execute a bulk create on a max of 200 objects per request'); } $createObjs = null; foreach ($objs as $obj) { if (!$createObjs){ $createObjs = new AutotaskObjects\CreateParam($obj); } else { $createObjs->Entities[] = $obj; } } return $this->_call('create', array($createObjs)); } public function update(AutotaskObjects\Entity $obj) { $params = new AutotaskObjects\UpdateParam($obj); return $this->_call('update', array($params)); } public function bulkUpdate(array $objs) { if (count($objs) > 200) { throw new \Exception('You can only execute a bulk update on a max of 200 objects per request'); } $updateObjs = null; $calls = array(); foreach ($objs as $obj) { if (!$updateObjs) { $updateObjs = new AutotaskObjects\UpdateParam($obj); } else { $updateObjs->Entities[] = $obj; } } return $this->_call('update', array($updateObjs)); } public function delete(AutotaskObjects\Entity $obj) { $params = new AutotaskObjects\DeleteParam($obj); return $this->_call('delete', array($params)); } public function bulkDelete(array $objs) { if (count($objs) > 200) { throw new \Exception('You can only execute a bulk delete on a max of 200 objects per request'); } $deleteObjs = null; $calls = array(); foreach ($objs as $obj) { if (!$deleteObjs) { $deleteObjs = new AutotaskObjects\DeleteParam($obj); } else { $deleteObjs->Entities[] = $obj; } } return $this->_call('delete', array($deleteObjs)); } public function CreateAttachment(AutotaskObjects\Entity $obj) { $params = new AutotaskObjects\CreateAttachment($obj); return $this->_call('CreateAttachment', array($params)); } public function query(AutotaskObjects\Query $obj) { $obj->asXml(); return $this->_call('query', array($obj)); } public function getUDFInfo($type) { $param = new AutotaskObjects\UDFParam($type); return $this->_call('getUDFInfo', array($param)); } public function getFieldInfo($type) { $fieldInfo = new AutotaskObjects\FieldInfo($type); return $this->_call('getFieldInfo', array($fieldInfo)); } public function getEntityInfo() { return $this->_call('getEntityInfo'); } public function getThresholdAndUsageInfo() { return $this->_call('getThresholdAndUsageInfo'); } public function getInvoiceMarkup($invoiceId, $type) { $invoiceMarkup = new AutotaskObjects\InvoiceMarkup(); $invoiceMarkup->InvoiceId = (int)$invoiceId; $invoiceMarkup->Format = $type; return $this->_call('GetInvoiceMarkup', array($invoiceMarkup)); } public function __doRequest($request, $location, $action, $version, $one_way = 0) { return parent::__doRequest($request, $location, $action, $version, $one_way); } private function _call($method, $params = array()) { return $this->__soapCall($method, $params); } // @codeCoerageIgnoreEnd } ?>`

**Comment by reynolek** [comment]
instead of requiring the client, be sure to require the autoloader.

The autoloader brings in all of the classes that the client needs to run (such as the ZoneInfo object, found in `src/AutotaskObjects/ZoneInfo.php`)

**Comment by Rikgeffen** [comment]
hi reynolek,

But is the output it gives oke?

**Comment by reynolek** [comment]
I dont know what that output is - it looks like the code in the client yes.

But you dont want to include the client, you want to include the autoloader which will bring everything in that you need. There is no real difference between `<?` vs `<?php` unless you dont have short tags enabled.

**Comment by Rikgeffen** [comment]
But how do i require the autoloader? do in need to change the autoload.php script. or do i need to make a new script. what do i need to write in it?

**Comment by reynolek** [comment]
You may need to pull down the latest version, but you require the autoloader by just doing `require_once __DIR__ . '<local path to autoloader.php>;'

Looking at the original post in this issue, you definitely need the newest version -- i fixed a bug with the directory separator logic.

**Comment by Rikgeffen** [comment]
i am sorry i have tryed it but it still doesnt work do you got time to show it on teamviewer or something that you can see what the problem is?

**Comment by reynolek** [comment]
Put this shell of a php file into the root of this repo.

Once you have it working, you can move it out of the repo, and then adjust the require_once path. Its pretty straight forward.
```php
require_once __DIR__ . '/src/autoload.php

<insert your php code here>
```

**Comment by Rikgeffen** [comment]
I'm sorry but I do not get it.
what do you mean by root and repo i am from the netherlands so i dont know al word can you be specific what script is wrong and how can i fix it. something like this : Composer.php is wrong becuase its the wrong path you need to edit it to .........

**Comment by reynolek** [comment]
To my knowledge, nothing is wrong in the repo after I pushed up the fix for the directory separators.

The root is the root folder (so the folder that contains all of the code you see (here)[https://github.com/opendns/autotask-php] and the repo is short for Repository, i.e. the github repository.

**Comment by Rikgeffen** [comment]
do you think that i dindt download the composer at the good way. if i placed your code that you type 9 days ago it says this : `Fatal error: Class 'ATWS\Client' not found in C:\xampp\htdocs\CM\AT\autotask-php-0.1.10\udf_query_example.php on line 11`
and a lot of other output but not he good one.

**Comment by reynolek** [comment]
If you are on windows, you need to use the windows directory separator instead of the *nix separator -- i.e. you need to use `\` rather than `/` in your directory paths.

`require_once __DIR__ . '/src/autoload.php';` needs to become `require_once __DIR__ . '\src\autoload.php';`, and you need to ensure that that path is actually correct depending on your directory structure.

**Comment by Rikgeffen** [comment]
I'm sorry but I tried it a few times but it does not work. I would like to make an appointment with you to look 30 minutes over my project. Because the back and forth typing doesnt go realy well. I hope that I can take a closer look to my project with you.

**Comment by reynolek** [comment]
Can you post your code/sample code and your folder structure? I am playing a guessing game without that. If its in a github repo that'd be awesome...

**Comment by Rikgeffen** [comment]
C:\xampp\htdocs\CM\AT\autotask-php-0.1.10 --->
	-src --->
		-AutotaskObjects --->
			-(Didnt change nothing in here)
		-udf_query_example
		-autoload
		-client
		-soap
	-CHANGELOG
	-composer
	-CONTRIBUTORS
	-LICENSE
	-README
	-ticket_create_example
	-udf_query_example	

[CHANGELOG.txt](https://github.com/opendns/autotask-php/files/1130292/CHANGELOG.txt)
[composer.txt](https://github.com/opendns/autotask-php/files/1130294/composer.txt)
[CONTRIBUTORS.txt](https://github.com/opendns/autotask-php/files/1130291/CONTRIBUTORS.txt)
[LICENSE.txt](https://github.com/opendns/autotask-php/files/1130290/LICENSE.txt)
[README.txt](https://github.com/opendns/autotask-php/files/1130289/README.txt)
[ticket_create_example.txt](https://github.com/opendns/autotask-php/files/1130293/ticket_create_example.txt)
[udf_query_example.txt](https://github.com/opendns/autotask-php/files/1130295/udf_query_example.txt)

[soap.txt](https://github.com/opendns/autotask-php/files/1130286/soap.txt)
[ATWSException.txt](https://github.com/opendns/autotask-php/files/1130285/ATWSException.txt)
[autoload.txt](https://github.com/opendns/autotask-php/files/1130287/autoload.txt)
[Client.txt](https://github.com/opendns/autotask-php/files/1130288/Client.txt)

**Comment by reynolek** [comment]
NOTE: You are 1 version behind, of which there was a bug fix that may prevent this from working. You should probably download 0.1.11 before proceeding.

Alright so lets try this:

In `C:\Xampp\htdocs\CM\AT\autotask-php-0.1.10` create a file called `test.php`.

Here's `test.php` (this was taken and slightly adapted from README.md):
```php
require_once __DIR__ . '\src\autoload.php';
$username = '<enter your autotask username>';
$authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';
$opts = array('trace' => 1);
$client = new ATWS\Client($authWsdl, $opts);
$zoneInfo = $client->getZoneInfo($username);

print_r($zoneInfo);
```

**Comment by Rikgeffen** [comment]
We are 1 stap closer!!

I download your project folder again and I didt what you sayed whit the test.php document.
but.... if the $authWsdl = 'vanderpol@EDSASSANDBOX.NL'; (this is my test in environment) it give this ERROR : _Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://pinotage.centrastage.net' : Premature end of data in tag HTML line 1 in C:\xampp\htdocs\CM\AT\autotask-php-master\src\Client.php:131 Stack trace: #0 C:\xampp\htdocs\CM\AT\autotask-php-master\src\Client.php(131): SoapClient->SoapClient('https://pinotag...', Array) #1 C:\xampp\htdocs\CM\AT\autotask-php-master\test.php(6): ATWS\Client->__construct('https://pinotag...', Array) #2 {main} thrown in C:\xampp\htdocs\CM\AT\autotask-php-master\src\Client.php on line 131_

and if i leave the URL like this : $authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';
its says : _stdClass Object ( [getZoneInfoResult] => ATWS\AutotaskObjects\ATWSZoneInfo Object ( [CI] => 807585 [DataBaseType] => [ErrorCode] => 0 [URL] => https://webservices16.autotask.net/ATServices/1.5/atws.asmx [WebUrl] => https://ww16.autotask.net/ ) )_

**Comment by SirPoot-** [comment]
@Rikgeffen why are you trying to connect to 'https://pinotage.centrastage.net'? That is not Autotask's PSA that's their RMM platform.

Are you trying to make your API calls to Autotask PSA or Autotask RMM?

**Comment by Rikgeffen** [comment]
no no i am sorry i am trying to connect to the PSA database.
what url i need to connect than?

**Comment by Rikgeffen** [comment]
do you know how to fix it?

**Comment by SirPoot-** [comment]
@Rikgeffen the $authWsdl needs to be 'https://webservices.autotask.net/atservices/1.5/atws.wsdl'. This is the default web services address and then it will redirect you to your proper zone which looks like yours is ww16.

As you mentioned, when you use that the proper authWsdl, your error code is 0. Not sure what exactly that means, but it should mean are authenticated and authorized. 

Can you change the $authWsdl to 'https://webservices.autotask.net/atservices/1.5/atws.wsdl' and then add and execute the following? This should return the ZERO (your company) information.

$AccountID = 0;
$Acctquery = new ATWS\AutotaskObjects\Query('Account');
$acctID = new ATWS\AutotaskObjects\QueryField('ID');
$acctID->addExpression('equals', $AccountID);
$Acctquery->addField($acctID);
$Acctresults = $client->query($Acctquery);
print_r($Acctresults);

Let me know the outcome.

**Comment by SirPoot-** [comment]
Looking at what @reynolek said on 7/7, you should perform the test.php file first, this will confirm your PHP environment is able to communicate with Autotask Web Services and then after a success, perform the account query.

**Comment by reynolek** [comment]
Yeah -- with the `test.php` file I literally provided you working code. From there I have to direct you to the [Usage](https://github.com/opendns/autotask-php#usage) section of the Readme.

**Comment by Rikgeffen** [comment]
@SirPoot- This is the output of you code >

**Your Code**
```
<?php
require_once __DIR__ . '\src\autoload.php';
$username = '***************************';
$password = '******';
$authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';
$opts = array('trace' => 1);
$client = new ATWS\Client($authWsdl, $opts);
$zoneInfo = $client->getZoneInfo($username);
$AccountID = 0;
$Acctquery = new ATWS\AutotaskObjects\Query('Account');
$acctID = new ATWS\AutotaskObjects\QueryField('ID');
$acctID->addExpression('equals', $AccountID);
$Acctquery->addField($acctID);
$Acctresults = $client->query($Acctquery);
print_r($Acctresults);

print_r($zoneInfo);
```

**Output**
_Fatal error: Uncaught SoapFault exception: [HTTP] Unauthorized in C:\xampp\htdocs\CM\AT\autotask-php-master\src\Client.php:252 Stack trace: #0 C:\xampp\htdocs\CM\AT\autotask-php-master\src\Client.php(252): SoapClient->__doRequest('<?xml version="...', 'https://webserv...', 'http://autotask...', 1, 0) #1 [internal function]: ATWS\Client->__doRequest('<?xml version="...', 'https://webserv...', 'http://autotask...', 1, 0) #2 C:\xampp\htdocs\CM\AT\autotask-php-master\src\Client.php(257): SoapClient->__soapCall('query', Array) #3 C:\xampp\htdocs\CM\AT\autotask-php-master\src\Client.php(217): ATWS\Client->_call('query', Array) #4 C:\xampp\htdocs\CM\AT\autotask-php-master\test.php(14): ATWS\Client->query(Object(ATWS\AutotaskObjects\Query)) #5 {main} thrown in C:\xampp\htdocs\CM\AT\autotask-php-master\src\Client.php on line 252_

**What i have done**
I used the test file but it dindt work so i used your code. I have fully download the code again on a newer version. i have try to placed it in a other folder but it dindt help.

**Comment by Rikgeffen** [comment]
@reynolek 

i used the test file and placed it in to the my hingest folder and change the pad but i still get the same ERROR. I tryed it in 5 diffrent directory's it only says **stdClass Object ( [getZoneInfoResult] => ATWS\AutotaskObjects\ATWSZoneInfo Object ( [CI] => 807585 [DataBaseType] => [ErrorCode] => 0 [URL] => https://webservices16.autotask.net/ATServices/1.5/atws.asmx [WebUrl] => https://ww16.autotask.net/ ) )** 

I all ready downloaded the new files and evrything maby it lays whit my pc specs or something. I use windows 10, Xampp to run the code, Neon eclipse to make the code, Composer in neon eclipse to get all the files.

**Comment by reynolek** [comment]
Responses with ErrorCode zero are successful. The object you are getting back contains the zone URL that you need to talk to for your account. 

If you follow the concepts in the readme and the text that's listed, you will find that you then need to create a new soap client with the zone URL in the response object, and submit your requests.

**Comment by Rikgeffen** [comment]
oke man.... i get the wrong output,

**<SCRIPT>**
<?php
```
require_once __DIR__ . '\AT\autotask-php-master\src\autoload.php';
$username = '***************************';
$password = '****************';
$authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';
$opts = array('trace' => 1);
$client = new ATWS\Client($authWsdl, $opts);
$zoneInfo = $client->getZoneInfo($username);


print_r($zoneInfo);

$authOpts = array(
		'login' => $username,
		'password' => $password,
		'trace' => 1,   // Allows us to debug by getting the XML requests sent
);
$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$client = new ATWS\Client($wsdl, $authOpts);

// Instantiate a Query object, designed to make complex
// queries simple.
$query = new ATWS\AutotaskObjects\Query('Contact');

// Add a QueryField with multiple expressions
$firstnameField = new ATWS\AutotaskObjects\QueryField('firstname');
// Multiple Expressions in a single Field results in a logical OR
$firstnameField->addExpression('BeginsWith', 'S');
$firstnameField->addExpression('Contains', 'e');

$query->addField($firstnameField);

$lastnameField = new ATWS\AutotaskObjects\QueryField('lastname');
$lastnameField->addExpression('BeginsWith', 'M');

// Add a second QueryField -- multiple Fields are ANDed together
$query->addField($lastnameField);

// print($query->asXml());
print_r($client->query($query));
```

**<OUTPUT>**
stdClass Object ( [getZoneInfoResult] => ATWS\AutotaskObjects\ATWSZoneInfo Object ( [CI] => 807585 [DataBaseType] => [ErrorCode] => 0 [URL] => https://webservices16.autotask.net/ATServices/1.5/atws.asmx [WebUrl] => https://ww16.autotask.net/ ) ) ATWS\AutotaskObjects\QueryResponse Object ( [queryResult] => ATWS\AutotaskObjects\ATWSResponse Object ( [EntityResults] => ATWS\AutotaskObjects\ArrayOfEntity Object ( [Entity] => ) [EntityResultType] => contact [EntityReturnInfoResults] => ATWS\AutotaskObjects\ArrayOfEntityReturnInfo Object ( [EntityReturnInfo] => [Fields] => [UserDefinedFields] => ) [Errors] => ATWS\AutotaskObjects\ArrayOfATWSError Object ( [ATWSError] => [Fields] => [UserDefinedFields] => ) [ReturnCode] => 1 ) ) 

**<Question>**
Can you send me your code en composer info and outpu so i can check the differents. And again i thank you for your help / support it means a lot to me.

**Comment by Rikgeffen** [comment]
****OUTPUT****
stdClass Object ( [getZoneInfoResult] => ATWS\AutotaskObjects\ATWSZoneInfo Object ( [CI] => 807585 [DataBaseType] => [ErrorCode] => 0 [URL] => https://webservices16.autotask.net/ATServices/1.5/atws.asmx [WebUrl] => https://ww16.autotask.net/ ) ) ATWS\AutotaskObjects\QueryResponse Object ( [queryResult] => ATWS\AutotaskObjects\ATWSResponse Object ( [EntityResults] => ATWS\AutotaskObjects\ArrayOfEntity Object ( [Entity] => ) [EntityResultType] => contact [EntityReturnInfoResults] => ATWS\AutotaskObjects\ArrayOfEntityReturnInfo Object ( [EntityReturnInfo] => [Fields] => [UserDefinedFields] => ) [Errors] => ATWS\AutotaskObjects\ArrayOfATWSError Object ( [ATWSError] => [Fields] => [UserDefinedFields] => ) [ReturnCode] => 1 ) ) 

****Question****

Can you send me your code en composer info and outpu so i can check the differents. And again i thank you for your help / support it means a lot to me.

**Comment by reynolek** [comment]
If you are having trouble getting a result back the first thing I will always recommend is simplifying the code down as much as possible -- having multiple expressions in your query is going to make things more confusing to debug.

Also, make sure you actually have a contact in your system that would match the criteria you are querying. If there are no results, it wouldnt surprise me if autotask returned an error code.

The code looks like it was copied straight from the readme, and last I checked, all that code was valid. So reduce the complexity of the query, and make sure you have something that will for sure match what you are querying.

**Comment by SirPoot-** [comment]
@Rikgeffen 

Keep it simple, once you have a grasp, then you can expand.

Try the following **code**.
```
<?php
require_once '../src/autoload.php';

$username = '..............';
$password = '...............';
$authWsdl = 'https://webservices.autotask.net/atservices/1.5/atws.wsdl';
$opts = array('trace' => 1);
$client = new ATWS\Client($authWsdl, $opts);
$zoneInfo = $client->getZoneInfo($username);

$authOpts = array(
		'login' => $username,
		'password' => $password,
		'trace' => 1,   // Allows us to debug by getting the XML requests sent
);
$wsdl = str_replace('.asmx', '.wsdl', $zoneInfo->getZoneInfoResult->URL);
$client = new ATWS\Client($wsdl, $authOpts);
$AccountID = 0;
$Acctquery = new ATWS\AutotaskObjects\Query('Account');
$acctID = new ATWS\AutotaskObjects\QueryField('ID');
$acctID->addExpression('equals', $AccountID);
$Acctquery->addField($acctID);
$Acctresults = $client->query($Acctquery);
print_r($Acctresults);
```

**Output** (This is a successful query and delete company data)

```
ATWS\AutotaskObjects\QueryResponse Object
(
    [queryResult] => ATWS\AutotaskObjects\ATWSResponse Object
        (
            [EntityResults] => ATWS\AutotaskObjects\ArrayOfEntity Object
                (
                    [Entity] => ATWS\AutotaskObjects\Account Object
                        (
                            [AccountName] => [DATA]
                            [AccountType] => [DATA]
                            [OwnerResourceID] => 4
                            [Phone] => [DATA]
                            [AccountNumber] => 0
                            [Active] => 1
                            [AdditionalAddressInformation] => 
                            [Address1] => [DATA]
                            [Address2] => 
                            [AlternativePhone1] => 
                            [AlternatePhone2] => 
                            [AssetValue] => 
                            [BillToAdditionalAddressInformation] => 
                            [BillToAddress1] => [DATA]
                            [BillToAddress2] => 
                            [BillToAddressToUse] => [DATA]
                            [BillToAttention] => 
                            [BillToCity] => [DATA]
                            [BillToCountryID] => [DATA]
                            [BillToState] => [DATA]
                            [BillToZipCode] => [DATA]
                            [City] => [DATA]
                            [ClientPortalActive] => 1
                            [CompetitorID] => 
                            [Country] => [DATA]
                            [CountryID] => [DATA]
                            [CreateDate] => 2002-05-16T06:56:33.81
                            [Fax] => [DATA]
                            [InvoiceMethod] => 
                            [InvoiceNonContractItemsToParentAccount] => 
                            [KeyAccountIcon] => 
                            [LastActivityDate] => 2017-06-09T09:43:33.157
                            [MarketSegmentID] => [DATA]
                            [ParentAccountID] => 
                            [PostalCode] => [DATA]
                            [SICCode] => 
                            [State] => [DATA]
                            [StockMarket] => 
                            [StockSymbol] => 
                            [TaskFireActive] => 
                            [TaxExempt] => 
                            [TaxID] => 
                            [TaxRegionID] => 
                            [TerritoryID] => [DATA]
                            [WebAddress] => [DATA]
                            [Fields] => 
                            [UserDefinedFields] => ATWS\AutotaskObjects\ArrayOfUserDefinedField Object
                                (
                                    [UserDefinedField] => [DATA]
                                        (
                                        )  

                                )

                            [id] => 0
                            [AlternatePhone1] => 
                            [QuoteTemplateID] => [DATA]
                            [QuoteEmailMessageID] => [DATA]
                            [InvoiceTemplateID] => [DATA]
                            [InvoiceEmailMessageID] => [DATA]
                            [CurrencyID] => [DATA]
                        )

                )

            [EntityResultType] => account
            [EntityReturnInfoResults] => ATWS\AutotaskObjects\ArrayOfEntityReturnInfo Object
                (
                    [EntityReturnInfo] => ATWS\AutotaskObjects\EntityReturnInfo Object
                        (
                            [DatabaseAction] => None
                            [DuplicateStatus] => ATWS\AutotaskObjects\EntityDuplicateStatus Object
                                (
                                    [Found] => 
                                    [Ignored] => 
                                    [MatchInfo] => 
                                    [Fields] => 
                                    [UserDefinedFields] => 
                                )

                            [EntityId] => 0
                            [Message] => 
                            [Fields] => 
                            [UserDefinedFields] => 
                        )

                    [Fields] => 
                    [UserDefinedFields] => 
                )

            [Errors] => ATWS\AutotaskObjects\ArrayOfATWSEr…

```

**Comment by Rikgeffen** [comment]
Thank you so match@sirpoot is works!!! 
it gives my data as output.
